DTSERWFOUR-635 Update-Select-Transfer-Method-graphql-call-to-fetch-fe…
hyperwallet/hyperwallet-android-sdk pull request #125
Opened 2021-06-15 12:02 UTC by shanavas123

…e-and-processing-time-only-for-the-country-currency-and-transfer-method-type-selected-for-performance

2021-06-15 12:27 UTC, SaiNarendran submitted a review, later dismissed

2021-06-17 11:27 UTC, rbanikPP requested changes
Please update read.md

2021-06-17 13:57 UTC, shanavas123 commented
> Please update read.md

updated

2021-06-18 03:42 UTC, SaiNarendran submitted a review, later dismissed

2021-06-18 16:09 UTC, aparthibanpaypal submitted a review, later dismissed

2021-06-18 17:19 UTC, jsaini-hw reviewed
Also update the connection timeout to 5 s instead of 10 sec

2021-06-18 17:19 UTC, jsaini-hw commented on core/src/main/java/com/hyperwallet/android/Hyperwallet.java
> +     * Returns the transfer method configuration key,TransferMethods, processing times, and fees set for the User that is associated
Transfer Method Types

2021-06-18 17:19 UTC, jsaini-hw commented on core/src/test/java/com/hyperwallet/android/transfermethod/RetrieveTransferMethodTypesFeeAndProcessingTimeConfigurationKeysTest.java
> +public class RetrieveTransferMethodTypesFeeAndProcessingTimeConfigurationKeysTest {
RetrieveTransferMethodTypesFeeAndProcessingTimeConfigurationKeysTest -> RetrieveTransferMethodTypesFeeAndProcessingTimeTest

2021-06-18 17:19 UTC, jsaini-hw commented on core/src/test/java/com/hyperwallet/android/transfermethod/RetrieveTransferMethodTypesFeeAndProcessingTimeConfigurationKeysTest.java
> +    public void testRetrieveTransferMethodConfigurationKeys_returnsFields() throws InterruptedException {
update test name to use RetrieveTransferMethodTypesFeesAndProcessingTimes instead of RetrieveTransferMethodConfigurationKeys

2021-06-18 17:19 UTC, jsaini-hw commented on core/src/test/java/com/hyperwallet/android/transfermethod/RetrieveTransferMethodTypesFeeAndProcessingTimeConfigurationKeysTest.java
> +    public void testRetrieveTransferMethodConfigurationKeys_withErrorAndData() throws InterruptedException {
same as above

2021-06-18 17:19 UTC, jsaini-hw commented on core/src/test/resources/tmc_get_keys_fee_processing_time_response.json
> +{
update file name to get_transfer_method_types_fee_processing_time_response

2021-06-21 07:07 UTC, shanavas123 commented on core/src/main/java/com/hyperwallet/android/Hyperwallet.java
> +     * Returns the transfer method configuration key,TransferMethods, processing times, and fees set for the User that is associated
fixed

2021-06-21 07:07 UTC, shanavas123 commented on core/src/test/java/com/hyperwallet/android/transfermethod/RetrieveTransferMethodTypesFeeAndProcessingTimeConfigurationKeysTest.java
> +public class RetrieveTransferMethodTypesFeeAndProcessingTimeConfigurationKeysTest {
renamed

2021-06-21 07:07 UTC, shanavas123 commented on core/src/test/java/com/hyperwallet/android/transfermethod/RetrieveTransferMethodTypesFeeAndProcessingTimeConfigurationKeysTest.java
> +    public void testRetrieveTransferMethodConfigurationKeys_returnsFields() throws InterruptedException {
renamed

2021-06-21 07:08 UTC, shanavas123 commented on core/src/test/java/com/hyperwallet/android/transfermethod/RetrieveTransferMethodTypesFeeAndProcessingTimeConfigurationKeysTest.java
> +    public void testRetrieveTransferMethodConfigurationKeys_withErrorAndData() throws InterruptedException {
renamed

2021-06-21 07:08 UTC, shanavas123 commented on core/src/test/resources/tmc_get_keys_fee_processing_time_response.json
> +{
renamed

2021-06-21 07:17 UTC, shanavas123 commented
> Also update the connection timeout to 5 s instead of 10 sec

Already time out as 10s
<img width="807" alt="Screenshot 2021-06-21 at 12 46 16 PM" src="https://user-images.githubusercontent.com/71114945/122721898-c8bdc100-d28e-11eb-940d-b9139f98e9a6.png">

2021-06-21 07:25 UTC, shanavas123 commented
> Also update the connection timeout to 5 s instead of 10 sec

Update timeout to 5 s

2021-06-21 08:27 UTC, SaiNarendran approved these changes

2021-06-21 13:44 UTC, aparthibanpaypal approved these changes

2021-06-21 16:22 UTC, jsaini-hw approved these changes

2021-06-21 16:23 UTC, merged